/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see core.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[4],{586:function(xa,ta,h){h.r(ta);var qa=h(0),oa=h(608),na=h(609),ja;(function(ka){ka[ka.EXTERNAL_XFDF_NOT_REQUESTED=0]="EXTERNAL_XFDF_NOT_REQUESTED";ka[ka.EXTERNAL_XFDF_NOT_AVAILABLE=1]="EXTERNAL_XFDF_NOT_AVAILABLE";ka[ka.EXTERNAL_XFDF_AVAILABLE=2]="EXTERNAL_XFDF_AVAILABLE"})(ja||(ja={}));xa=function(){function ka(fa){this.ba=fa;this.state=ja.EXTERNAL_XFDF_NOT_REQUESTED}ka.prototype.Qxa=function(){var fa=this;return function(x,
z,r){return Object(qa.b)(fa,void 0,void 0,function(){var n,f,b,a,e,w,y,ba=this,ha;return Object(qa.d)(this,function(aa){switch(aa.label){case 0:if(this.state!==ja.EXTERNAL_XFDF_NOT_REQUESTED)return[3,2];n=this.ba.getDocument().Xx();return[4,this.yva(n)];case 1:f=aa.aa(),b=this.opa(f),this.rS=null!==(ha=null===b||void 0===b?void 0:b.parse())&&void 0!==ha?ha:null,this.state=null===this.rS?ja.EXTERNAL_XFDF_NOT_AVAILABLE:ja.EXTERNAL_XFDF_AVAILABLE,aa.label=2;case 2:if(this.state===ja.EXTERNAL_XFDF_NOT_AVAILABLE)return r(x),
[2];a=new DOMParser;e=a.parseFromString(x,"text/xml");z.forEach(function(ea){ba.merge(e,ba.rS,ea-1)});w=new XMLSerializer;y=w.serializeToString(e);r(y);return[2]}})})}};ka.prototype.XX=function(fa){this.yva=fa};ka.prototype.Xf=function(){this.rS=void 0;this.state=ja.EXTERNAL_XFDF_NOT_REQUESTED};ka.prototype.opa=function(fa){return fa?Array.isArray(fa)?new oa.a(fa):"string"!==typeof fa?null:(new DOMParser).parseFromString(fa,"text/xml").querySelector("xfdf > add")?new oa.a(fa):new na.a(fa):null};ka.prototype.merge=
function(fa,x,z){var r=this;0===z&&(this.pBa(fa,x.St),this.rBa(fa,x.ZR));var n=x.ea[z];n&&(this.sBa(fa,n.qr),this.uBa(fa,n.yfa,x.CC),this.tBa(fa,n.page,z),this.qBa(fa,n.X4));n=this.ba.Cb();if(z===n-1){var f=x.CC;Object.keys(f).forEach(function(b){f[b].mU||r.i$(fa,b,f[b])})}};ka.prototype.pBa=function(fa,x){null!==x&&(fa=this.BB(fa),this.uv(fa,"calculation-order",x))};ka.prototype.rBa=function(fa,x){null!==x&&(fa=this.BB(fa),this.uv(fa,"document-actions",x))};ka.prototype.sBa=function(fa,x){var z=
this,r=this.AB(fa.querySelector("xfdf"),"annots");Object.keys(x).forEach(function(n){z.uv(r,'[name="'.concat(n,'"]'),x[n])})};ka.prototype.uBa=function(fa,x,z){var r=this;if(0!==x.length){var n=this.BB(fa);x.forEach(function(f){var b=f.getAttribute("field"),a=z[b];a&&(r.i$(fa,b,a),r.uv(n,"null",f))})}};ka.prototype.i$=function(fa,x,z){var r=this.BB(fa),n=r.querySelector('ffield[name="'.concat(x,'"]'));null!==z.XJ&&null===n&&this.uv(r,'ffield[name="'.concat(x,'"]'),z.XJ);fa=this.AB(fa.querySelector("xfdf"),
"xfdf > fields","fields");x=x.split(".");this.UW(fa,x,0,z.value);z.mU=!0};ka.prototype.tBa=function(fa,x,z){null!==x&&(fa=this.BB(fa),fa=this.AB(fa,"pages"),this.uv(fa,'[number="'.concat(z+1,'"]'),x))};ka.prototype.qBa=function(fa,x){Object.keys(x).forEach(function(z){(z=fa.querySelector('annots [name="'.concat(z,'"]')))&&z.parentElement.removeChild(z)})};ka.prototype.UW=function(fa,x,z,r){if(z===x.length)x=document.createElementNS("","value"),x.textContent=r,this.uv(fa,"value",x);else{var n=x[z];
this.AB(fa,'[name="'.concat(n,'"]'),"field").setAttribute("name",n);fa=fa.querySelectorAll('[name="'.concat(n,'"]'));1===fa.length?this.UW(fa[0],x,z+1,r):(n=this.Jta(fa),this.UW(z===x.length-1?n:this.xKa(fa,n),x,z+1,r))}};ka.prototype.Jta=function(fa){for(var x=null,z=0;z<fa.length;z++){var r=fa[z];if(0===r.childElementCount||1===r.childElementCount&&"value"===r.children[0].tagName){x=r;break}}return x};ka.prototype.xKa=function(fa,x){for(var z=0;z<fa.length;z++)if(fa[z]!==x)return fa[z];return null};
ka.prototype.uv=function(fa,x,z){x=fa.querySelector(x);null!==x&&fa.removeChild(x);fa.appendChild(z)};ka.prototype.BB=function(fa){var x=fa.querySelector("pdf-info");if(null!==x)return x;x=this.AB(fa.querySelector("xfdf"),"pdf-info");x.setAttribute("xmlns","http://www.pdftron.com/pdfinfo");x.setAttribute("version","2");x.setAttribute("import-version","4");return x};ka.prototype.AB=function(fa,x,z){var r=fa.querySelector(x);if(null!==r)return r;r=document.createElementNS("",z||x);fa.appendChild(r);
return r};return ka}();ta["default"]=xa},597:function(xa,ta){xa=function(){function h(){}h.prototype.jI=function(qa){var oa={St:null,ZR:null,CC:{},ea:{}};qa=(new DOMParser).parseFromString(qa,"text/xml");oa.St=qa.querySelector("pdf-info calculation-order");oa.ZR=qa.querySelector("pdf-info document-actions");oa.CC=this.RCa(qa);oa.ea=this.eDa(qa);return oa};h.prototype.RCa=function(qa){var oa=qa.querySelector("fields");qa=qa.querySelectorAll("pdf-info > ffield");if(null===oa&&null===qa)return{};var na=
{};this.Bla(na,oa);this.zla(na,qa);return na};h.prototype.Bla=function(qa,oa){if(null!==oa&&oa.children){for(var na=[],ja=0;ja<oa.children.length;ja++){var ka=oa.children[ja];na.push({name:ka.getAttribute("name"),element:ka})}for(;0!==na.length;)for(oa=na.shift(),ja=0;ja<oa.element.children.length;ja++)ka=oa.element.children[ja],"value"===ka.tagName?qa[oa.name]={value:ka.textContent,XJ:null,mU:!1}:ka.children&&na.push({name:"".concat(oa.name,".").concat(ka.getAttribute("name")),element:ka})}};h.prototype.zla=
function(qa,oa){oa.forEach(function(na){var ja=na.getAttribute("name");qa[ja]?qa[ja].XJ=na:qa[ja]={value:null,XJ:na,mU:!1}})};h.prototype.eDa=function(qa){var oa=this,na={};qa.querySelectorAll("pdf-info widget").forEach(function(ja){var ka=parseInt(ja.getAttribute("page"),10)-1;oa.pL(na,ka);na[ka].yfa.push(ja)});qa.querySelectorAll("pdf-info page").forEach(function(ja){var ka=parseInt(ja.getAttribute("number"),10)-1;oa.pL(na,ka);na[ka].page=ja});this.Z6(qa).forEach(function(ja){var ka=parseInt(ja.getAttribute("page"),
10),fa=ja.getAttribute("name");oa.pL(na,ka);na[ka].qr[fa]=ja});this.I6(qa).forEach(function(ja){var ka=parseInt(ja.getAttribute("page"),10);ja=ja.textContent;oa.pL(na,ka);na[ka].X4[ja]=!0});return na};h.prototype.pL=function(qa,oa){qa[oa]||(qa[oa]={qr:{},X4:{},yfa:[],page:null})};return h}();ta.a=xa},608:function(xa,ta,h){var qa=h(0),oa=h(1);h.n(oa);xa=function(na){function ja(ka){var fa=na.call(this)||this;fa.sta=Array.isArray(ka)?ka:[ka];return fa}Object(qa.c)(ja,na);ja.prototype.parse=function(){var ka=
this,fa={St:null,ZR:null,CC:{},ea:{}};this.sta.forEach(function(x){fa=Object(oa.merge)(fa,ka.jI(x))});return fa};ja.prototype.Z6=function(ka){var fa=[];ka.querySelectorAll("add > *").forEach(function(x){fa.push(x)});ka.querySelectorAll("modify > *").forEach(function(x){fa.push(x)});return fa};ja.prototype.I6=function(ka){return ka.querySelectorAll("delete > *")};return ja}(h(597).a);ta.a=xa},609:function(xa,ta,h){var qa=h(0);xa=function(oa){function na(ja){var ka=oa.call(this)||this;ka.tta=ja;return ka}
Object(qa.c)(na,oa);na.prototype.parse=function(){return this.jI(this.tta)};na.prototype.Z6=function(ja){return ja.querySelectorAll("annots > *")};na.prototype.I6=function(){return[]};return na}(h(597).a);ta.a=xa}}]);}).call(this || window)
